### ISSUE TITLE
'single_file' is no longer supported

### ISSUE THREAD

**Issue by regisd** [jflex-de/bazel_rules#12]
**Change the title**: A clear and concise description of what the bug is.

**To Reproduce**
> Steps to reproduce the behavior:

1. Run command 'bazel build //java/...'

> ERROR: /Users/regisd/Projects/jflex_bazel_rules/jflex/jflex.bzl:47:21: Traceback (most recent call last):
> 	File "/Users/regisd/Projects/jflex_bazel_rules/jflex/jflex.bzl", line 38
> 		rule(<3 more arguments>)
> 	File "/Users/regisd/Projects/jflex_bazel_rules/jflex/jflex.bzl", line 47, in rule
> 		attr.label(allow_files = True, <2 more arguments>)
> 'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
> ERROR: error loading package 'java/jflex/examples/helloworld': Extension file 'jflex/jflex.bzl' has errors
> 

**Expected behavior**
Example compiles.

**Environnment**
> release: release 1.1.0

**Comment by regisd** [comment]
This was deprecated in https://github.com/bazelbuild/bazel/commit/e506858c14d9ffceedbb22988f7c65fe70df5536
in Bazel 0.17.1
